Traceback (most recent call last):
  File "C:\Users\smith6jt\miniforge3\envs\KINTSUGI\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\smith6jt\miniforge3\envs\KINTSUGI\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\smith6jt\miniforge3\envs\KINTSUGI\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\smith6jt\miniforge3\envs\KINTSUGI\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\smith6jt\miniforge3\envs\KINTSUGI\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\smith6jt\miniforge3\envs\KINTSUGI\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\smith6jt\miniforge3\envs\KINTSUGI\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
filter_channel = 'Ki67'
nuclear_exclude = False

pixel_cluster_utils.filter_with_nuclear(
    fovs=fovs,
    tiff_dir=tiff_dir,
    seg_dir=os.path.join(base_dir, segmentation_dir),
    channel=filter_channel,
    nuc_seg_suffix="_nuclear.tiff",
    exclude=nuclear_exclude
)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn[9], line 4[0m
[0;32m      1[0m filter_channel [38;5;241m=[39m [38;5;124m'[39m[38;5;124mKi67[39m[38;5;124m'[39m
[0;32m      2[0m nuclear_exclude [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m----> 4[0m [43mpixel_cluster_utils[49m[38;5;241;43m.[39;49m[43mfilter_with_nuclear[49m(
[0;32m      5[0m     fovs[38;5;241m=[39mfovs,
[0;32m      6[0m     tiff_dir[38;5;241m=[39mtiff_dir,
[0;32m      7[0m     seg_dir[38;5;241m=[39mos[38;5;241m.[39mpath[38;5;241m.[39mjoin(base_dir, segmentation_dir),
[0;32m      8[0m     channel[38;5;241m=[39mfilter_channel,
[0;32m      9[0m     nuc_seg_suffix[38;5;241m=[39m[38;5;124m"[39m[38;5;124m_nuclear.tiff[39m[38;5;124m"[39m,
[0;32m     10[0m     exclude[38;5;241m=[39mnuclear_exclude
[0;32m     11[0m )

[1;31mAttributeError[0m: module 'ark.phenotyping.pixel_cluster_utils' has no attribute 'filter_with_nuclear'

